In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("/home/koushik/modelling.csv", parse_dates=['VALUATION'])

/home/koushik/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
data

Unnamed: 0 GRPNUM  VALUATION  STATUS  SIC_Code Effective_Date  \
0                0  10001 2015-01-31  ACTIVE    8299.0     01-01-2012   
1                1  10001 2015-02-28  ACTIVE    8299.0     01-01-2012   
2                2  10001 2015-03-31  ACTIVE    8299.0     01-01-2012   
3                3  10001 2015-04-30  ACTIVE    8299.0     01-01-2012   
4                4  10001 2015-05-31  ACTIVE    8299.0     01-01-2012   
5                5  10001 2015-06-30  ACTIVE    8299.0     01-01-2012   
6                6  10001 2015-07-31  ACTIVE    8299.0     01-01-2012   
7                7  10001 2015-08-31  ACTIVE    8299.0     01-01-2012   
8                8  10001 2015-09-30  ACTIVE    8299.0     01-01-2012   
9                9  10001 2015-10-31  ACTIVE    8299.0     01-01-2012   
10              10  10001 2015-11-30  ACTIVE    8299.0     01-01-2012   
11              11  10001 2015-12-31  ACTIVE    8299.0     01-01-2012   
12              12  10001 2016-01-31  ACTIVE    8299.0     01-01-2012   
13              13  10001 2016-02-29  ACTIVE    8299.0     01-01-2012   
14              14  10001 2016-03-31  ACTIVE    8299.0     01-01-2012   
15              15  10001 2016-04-30  ACTIVE    8299.0     01-01-2012   
16              16  10001 2016-05-31  ACTIVE    8299.0     01-01-2012   
17              17  10001 2016-06-30  Active    8299.0     01-01-2012   
18              18  10001 2016-07-31  ACTIVE    8299.0     01-01-2012   
19              19  10001 2016-08-31  ACTIVE    8299.0     01-01-2012   
20              20  10001 2016-09-30  ACTIVE    8299.0     01-01-2012   
21              21  10001 2016-10-31  ACTIVE    8299.0     01-01-2012   
22              22  10001 2016-11-30  ACTIVE    8299.0     01-01-2012   
23              23  10001 2016-12-31  ACTIVE    8299.0     01-01-2012   
24              24  10001 2017-01-31  ACTIVE    8299.0     01-01-2012   
25              25  10001 2017-02-28  ACTIVE    8299.0     01-01-2012   
26              26  10003 2015-01-31  ACTIVE    5211.0     01-01-2012   
27              27  10003 2015-02-28  ACTIVE    5211.0     01-01-2012   
28              28  10003 2015-03-31  ACTIVE    5211.0     01-01-2012   
29              29  10003 2015-04-30  ACTIVE    5211.0     01-01-2012   
...            ...    ...        ...     ...       ...            ...   
182989      182989     A1 2016-06-30  Active       NaN     01-01-2010   
182990      182990     A1 2016-07-31  ACTIVE       NaN     01-01-2010   
182991      182991     A1 2016-08-31  ACTIVE       NaN     01-01-2010   
182992      182992     A1 2016-09-30  ACTIVE       NaN     01-01-2010   
182993      182993     A1 2016-10-31  ACTIVE       NaN     01-01-2010   
182994      182994     A1 2016-11-30  ACTIVE       NaN     01-01-2010   
182995      182995     A1 2016-12-31  ACTIVE       NaN     01-01-2010   
182996      182996     A1 2017-01-31  ACTIVE       NaN     01-01-2010   
182997      182997     A1 2017-02-28  ACTIVE       NaN     01-01-2010   
182998      182998     A2 2015-01-31  ACTIVE       NaN     01-03-2010   
182999      182999     A2 2015-02-28  ACTIVE       NaN     01-03-2010   
183000      183000     A2 2015-03-31  ACTIVE       NaN     01-03-2010   
183001      183001     A2 2015-04-30  ACTIVE       NaN     01-03-2010   
183002      183002     A2 2015-05-31  ACTIVE       NaN     01-03-2010   
183003      183003     A2 2015-06-30  ACTIVE       NaN     01-03-2010   
183004      183004     A2 2015-07-31  ACTIVE       NaN     01-03-2010   
183005      183005     A2 2015-08-31  ACTIVE       NaN     01-03-2010   
183006      183006     A2 2015-09-30  ACTIVE       NaN     01-03-2010   
183007      183007     A2 2015-10-31  ACTIVE       NaN     01-03-2010   
183008      183008     A2 2015-11-30  ACTIVE       NaN     01-03-2010   
183009      183009     A2 2015-12-31  ACTIVE       NaN     01-03-2010   
183010      183010     A2 2016-01-31  ACTIVE       NaN     01-03-2010   
183011      183011     A2 2016-02-29  ACTIVE       NaN     01-03-2

In [5]:
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

/home/koushik/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
data.columns

Index([u'Unnamed: 0', u'GRPNUM', u'VALUATION', u'STATUS', u'SIC_Code',
       u'Effective_Date', u'EE_Count', u'Tenure_Months', u'Tenure_Months1',
       u'Apps_Recd', u'Apps_Proc', u'Apps_Proc_Percent', u'Applied_Premium',
       u'AppliedPremium_L1', u'AppliedPremiumL1_Percent', u'AppliedPremium_L2',
       u'AppliedPremiumL2_Percent', u'AppliedPremium_L3',
       u'AppliedPremiumL3_Percent', u'Claims_Total', u'NoBene', u'NoCert',
       u'NoBenePercent', u'NoCertPercent', u'GROSS_AP', u'GROSSAP_L1',
       u'GrossAPL1_Percent', u'GROSSAP_L2', u'GrossAPL2_Percent',
       u'GROSSAP_L3', u'GrossAPL3_Percent', u'Eff_Date', u'Enrollment_Data',
       u'Account_Implementation_Coordinator', u'Account_Service_Coordinator',
       u'G0138_Status_Timestamp', u'Enrollment_Star_Timestamp',
       u'G0138_received', u'Min_Task_Entry_Date', u'Setup_Complete',
       u'Specific_Suspense', u'Unknown_Suspense', u'Total_Suspense',
       u'TotalSuspense_L1', u'TotalSuspenseL1_Percent', u'TotalSuspen

In [7]:
data = data.fillna(0)

In [8]:
import datetime
import time

In [9]:
boundary_date = datetime.datetime.strptime('17-01-31', '%y-%m-%d').date()
mod_data = data[data.VALUATION < boundary_date]

In [10]:
mod_data

Unnamed: 0 GRPNUM  VALUATION  STATUS  SIC_Code Effective_Date  \
0                0  10001 2015-01-31  ACTIVE    8299.0     01-01-2012   
1                1  10001 2015-02-28  ACTIVE    8299.0     01-01-2012   
2                2  10001 2015-03-31  ACTIVE    8299.0     01-01-2012   
3                3  10001 2015-04-30  ACTIVE    8299.0     01-01-2012   
4                4  10001 2015-05-31  ACTIVE    8299.0     01-01-2012   
5                5  10001 2015-06-30  ACTIVE    8299.0     01-01-2012   
6                6  10001 2015-07-31  ACTIVE    8299.0     01-01-2012   
7                7  10001 2015-08-31  ACTIVE    8299.0     01-01-2012   
8                8  10001 2015-09-30  ACTIVE    8299.0     01-01-2012   
9                9  10001 2015-10-31  ACTIVE    8299.0     01-01-2012   
10              10  10001 2015-11-30  ACTIVE    8299.0     01-01-2012   
11              11  10001 2015-12-31  ACTIVE    8299.0     01-01-2012   
12              12  10001 2016-01-31  ACTIVE    8299.0     01-01-2012   
13              13  10001 2016-02-29  ACTIVE    8299.0     01-01-2012   
14              14  10001 2016-03-31  ACTIVE    8299.0     01-01-2012   
15              15  10001 2016-04-30  ACTIVE    8299.0     01-01-2012   
16              16  10001 2016-05-31  ACTIVE    8299.0     01-01-2012   
17              17  10001 2016-06-30  Active    8299.0     01-01-2012   
18              18  10001 2016-07-31  ACTIVE    8299.0     01-01-2012   
19              19  10001 2016-08-31  ACTIVE    8299.0     01-01-2012   
20              20  10001 2016-09-30  ACTIVE    8299.0     01-01-2012   
21              21  10001 2016-10-31  ACTIVE    8299.0     01-01-2012   
22              22  10001 2016-11-30  ACTIVE    8299.0     01-01-2012   
23              23  10001 2016-12-31  ACTIVE    8299.0     01-01-2012   
26              26  10003 2015-01-31  ACTIVE    5211.0     01-01-2012   
27              27  10003 2015-02-28  ACTIVE    5211.0     01-01-2012   
28              28  10003 2015-03-31  ACTIVE    5211.0     01-01-2012   
29              29  10003 2015-04-30  ACTIVE    5211.0     01-01-2012   
30              30  10003 2015-05-31  ACTIVE    5211.0     01-01-2012   
31              31  10003 2015-06-30  ACTIVE    5211.0     01-01-2012   
...            ...    ...        ...     ...       ...            ...   
182987      182987     A1 2016-04-30  ACTIVE       0.0     01-01-2010   
182988      182988     A1 2016-05-31  ACTIVE       0.0     01-01-2010   
182989      182989     A1 2016-06-30  Active       0.0     01-01-2010   
182990      182990     A1 2016-07-31  ACTIVE       0.0     01-01-2010   
182991      182991     A1 2016-08-31  ACTIVE       0.0     01-01-2010   
182992      182992     A1 2016-09-30  ACTIVE       0.0     01-01-2010   
182993      182993     A1 2016-10-31  ACTIVE       0.0     01-01-2010   
182994      182994     A1 2016-11-30  ACTIVE       0.0     01-01-2010   
182995      182995     A1 2016-12-31  ACTIVE       0.0     01-01-2010   
182998      182998     A2 2015-01-31  ACTIVE       0.0     01-03-2010   
182999      182999     A2 2015-02-28  ACTIVE       0.0     01-03-2010   
183000      183000     A2 2015-03-31  ACTIVE       0.0     01-03-2010   
183001      183001     A2 2015-04-30  ACTIVE       0.0     01-03-2010   
183002      183002     A2 2015-05-31  ACTIVE       0.0     01-03-2010   
183003      183003     A2 2015-06-30  ACTIVE       0.0     01-03-2010   
183004      183004     A2 2015-07-31  ACTIVE       0.0     01-03-2010   
183005      183005     A2 2015-08-31  ACTIVE       0.0     01-03-2010   
183006      183006     A2 2015-09-30  ACTIVE       0.0     01-03-2010   
183007      183007     A2 2015-10-31  ACTIVE       0.0     01-03-2010   
183008      183008     A2 2015-11-30  ACTIVE       0.0     01-03-2010   
183009      183009     A2 2015-12-31  ACTIVE       0.0     01-03-2010   
183010      183010     A2 2016-01-31  ACTIVE       0.0     01-03-2010   
183011      183011     A2 2016-02-29  ACTIVE       0.0     01-03-2

In [11]:
mod_data.shape

(169207, 63)

In [12]:
train_data = mod_data.iloc[0:130000,:]
test_data = mod_data.iloc[130000:,:]

In [13]:
x_train = train_data[['Tenure_Months','Apps_Proc_Percent','Applied_Premium','NoBenePercent','NoCertPercent','GROSS_AP','G0138_received','Setup_Complete','Total_Suspense','TotalCases','Active_Cases']]
x_test = test_data[['Tenure_Months','Apps_Proc_Percent','Applied_Premium','NoBenePercent','NoCertPercent','GROSS_AP','G0138_received','Setup_Complete','Total_Suspense','TotalCases','Active_Cases']]
y_train = train_data[['y']]
y_test = test_data[['y']]

In [14]:
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train, y_train)

/home/koushik/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
y_pred = classifier.predict(x_test)
y_pred = y_pred.reshape(39207,1)

In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[    3     0     0     0   326]
 [    0     0     0     0   313]
 [    0     0     0     0   305]
 [    0     0     0     0   308]
 [    1     0     0     0 37951]]


In [17]:
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(x_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.97


In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.75      0.01      0.02       329
          1       0.00      0.00      0.00       313
          2       0.00      0.00      0.00       305
          3       0.00      0.00      0.00       308
         12       0.97      1.00      0.98     37952

avg / total       0.94      0.97      0.95     39207



/home/koushik/anaconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [21]:
for i in range(len(y_pred)):
    if y_pred[i] != 12:
        print y_pred[i]

[0]
[0]
[0]
[0]


In [22]:
y_pred[15694]

array([0])

In [23]:
y_test.iloc[15694]

y    0
Name: 157763, dtype: int64

In [24]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(x_train, y_train)  

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [25]:
y_pred = classifier.predict(x_test)  

In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[  244     4     1     2    78]
 [    4    11     3     3   292]
 [    1    11     2     5   286]
 [    2     8     6     8   284]
 [  115   426   452   405 36554]]


In [27]:
print('Accuracy of Decision Tree classifier on test set: {:.2f}'.format(classifier.score(x_test, y_test)))

Accuracy of Decision Tree classifier on test set: 0.94


In [28]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.67      0.74      0.70       329
          1       0.02      0.04      0.03       313
          2       0.00      0.01      0.01       305
          3       0.02      0.03      0.02       308
         12       0.97      0.96      0.97     37952

avg / total       0.95      0.94      0.94     39207



In [29]:
for i in range(len(y_pred)):
    if y_pred[i] != 12:
        print y_pred[i]
        print y_test.iloc[i]

0
y    0
Name: 140901, dtype: int64
2
y    12
Name: 140931, dtype: int64
1
y    12
Name: 140936, dtype: int64
2
y    12
Name: 140969, dtype: int64
1
y    12
Name: 140979, dtype: int64
1
y    12
Name: 140981, dtype: int64
1
y    12
Name: 140983, dtype: int64
2
y    12
Name: 141052, dtype: int64
2
y    12
Name: 141114, dtype: int64
2
y    12
Name: 141145, dtype: int64
3
y    12
Name: 141185, dtype: int64
3
y    12
Name: 141193, dtype: int64
3
y    12
Name: 141195, dtype: int64
1
y    12
Name: 141211, dtype: int64
3
y    12
Name: 141394, dtype: int64
2
y    12
Name: 141412, dtype: int64
0
y    0
Name: 141610, dtype: int64
1
y    12
Name: 141673, dtype: int64
0
y    0
Name: 141691, dtype: int64
1
y    12
Name: 141704, dtype: int64
1
y    12
Name: 141707, dtype: int64
3
y    12
Name: 141727, dtype: int64
3
y    12
Name: 141728, dtype: int64
1
y    12
Name: 141729, dtype: int64
1
y    12
Name: 141730, dtype: int64
1
y    12
Name: 141731, dtype: int64
1
y    12
Name: 141732, dtype: int64
1
y 

Name: 149717, dtype: int64
1
y    12
Name: 149718, dtype: int64
1
y    12
Name: 149719, dtype: int64
1
y    12
Name: 149720, dtype: int64
1
y    12
Name: 149721, dtype: int64
1
y    12
Name: 149722, dtype: int64
1
y    12
Name: 149723, dtype: int64
1
y    12
Name: 149724, dtype: int64
1
y    12
Name: 149725, dtype: int64
1
y    12
Name: 149726, dtype: int64
1
y    12
Name: 149727, dtype: int64
3
y    12
Name: 149733, dtype: int64
2
y    12
Name: 149756, dtype: int64
3
y    12
Name: 149816, dtype: int64
3
y    12
Name: 149829, dtype: int64
3
y    12
Name: 149831, dtype: int64
3
y    12
Name: 149895, dtype: int64
0
y    0
Name: 149906, dtype: int64
1
y    12
Name: 149970, dtype: int64
1
y    12
Name: 149971, dtype: int64
2
y    12
Name: 150032, dtype: int64
0
y    12
Name: 150055, dtype: int64
1
y    12
Name: 150056, dtype: int64
0
y    12
Name: 150057, dtype: int64
0
y    12
Name: 150058, dtype: int64
0
y    12
Name: 150060, dtype: int64
0
y    12
Name: 150061, dtype: int64
2
y    12
Na

y    0
Name: 157694, dtype: int64
0
y    0
Name: 157763, dtype: int64
2
y    12
Name: 157777, dtype: int64
2
y    12
Name: 157853, dtype: int64
0
y    0
Name: 157865, dtype: int64
1
y    12
Name: 157959, dtype: int64
0
y    0
Name: 157964, dtype: int64
0
y    12
Name: 157976, dtype: int64
1
y    0
Name: 158036, dtype: int64
3
y    12
Name: 158044, dtype: int64
3
y    12
Name: 158143, dtype: int64
0
y    0
Name: 158161, dtype: int64
2
y    12
Name: 158166, dtype: int64
2
y    12
Name: 158169, dtype: int64
2
y    12
Name: 158297, dtype: int64
2
y    12
Name: 158299, dtype: int64
1
y    12
Name: 158318, dtype: int64
0
y    0
Name: 158357, dtype: int64
0
y    0
Name: 158410, dtype: int64
2
y    12
Name: 158455, dtype: int64
2
y    12
Name: 158457, dtype: int64
2
y    12
Name: 158458, dtype: int64
2
y    12
Name: 158459, dtype: int64
2
y    12
Name: 158460, dtype: int64
0
y    0
Name: 158481, dtype: int64
3
y    12
Name: 158601, dtype: int64
3
y    12
Name: 158650, dtype: int64
2
y    12
Na

y    0
Name: 168738, dtype: int64
0
y    0
Name: 168743, dtype: int64
3
y    12
Name: 168816, dtype: int64
3
y    12
Name: 168832, dtype: int64
2
y    12
Name: 168970, dtype: int64
2
y    12
Name: 169015, dtype: int64
1
y    12
Name: 169036, dtype: int64
3
y    12
Name: 169057, dtype: int64
0
y    12
Name: 169060, dtype: int64
0
y    12
Name: 169061, dtype: int64
0
y    12
Name: 169062, dtype: int64
0
y    12
Name: 169126, dtype: int64
1
y    12
Name: 169127, dtype: int64
0
y    12
Name: 169128, dtype: int64
0
y    12
Name: 169129, dtype: int64
0
y    12
Name: 169130, dtype: int64
0
y    12
Name: 169131, dtype: int64
0
y    12
Name: 169132, dtype: int64
0
y    12
Name: 169133, dtype: int64
0
y    12
Name: 169134, dtype: int64
0
y    12
Name: 169135, dtype: int64
1
y    12
Name: 169162, dtype: int64
3
y    12
Name: 169208, dtype: int64
3
y    12
Name: 169214, dtype: int64
0
y    0
Name: 169285, dtype: int64
2
y    12
Name: 169332, dtype: int64
1
y    2
Name: 169459, dtype: int64
0
y    

Name: 177373, dtype: int64
3
y    12
Name: 177424, dtype: int64
1
y    12
Name: 177560, dtype: int64
2
y    12
Name: 177619, dtype: int64
2
y    12
Name: 177636, dtype: int64
1
y    12
Name: 177671, dtype: int64
0
y    12
Name: 177734, dtype: int64
1
y    12
Name: 177735, dtype: int64
0
y    0
Name: 177757, dtype: int64
0
y    0
Name: 177776, dtype: int64
0
y    0
Name: 177806, dtype: int64
1
y    12
Name: 177833, dtype: int64
1
y    12
Name: 177834, dtype: int64
0
y    12
Name: 177879, dtype: int64
0
y    0
Name: 177970, dtype: int64
0
y    0
Name: 177976, dtype: int64
1
y    12
Name: 178032, dtype: int64
2
y    12
Name: 178033, dtype: int64
0
y    12
Name: 178052, dtype: int64
0
y    0
Name: 178140, dtype: int64
1
y    12
Name: 178185, dtype: int64
1
y    12
Name: 178187, dtype: int64
0
y    12
Name: 178189, dtype: int64
3
y    12
Name: 178230, dtype: int64
0
y    0
Name: 178259, dtype: int64
2
y    12
Name: 178264, dtype: int64
0
y    0
Name: 178279, dtype: int64
3
y    12
Name: 178

In [90]:
maj_data = mod_data[mod_data.y>3]
maj_data = maj_data.iloc[0:15832 , :]

In [91]:
min_data = mod_data[mod_data.y<4]
min_data = min_data[min_data.y>0]
min_data.shape

(4692, 63)

In [92]:
frames = [maj_data , min_data]
balanced_data = pd.concat(frames)

In [93]:
balanced_data.shape

(20524, 63)

In [94]:
train_data = balanced_data.iloc[0:18000,:]
test_data = balanced_data.iloc[18000:,:]
x_train = train_data[['Tenure_Months','Apps_Proc_Percent','Applied_Premium','NoBenePercent','NoCertPercent','GROSS_AP','G0138_received','Setup_Complete','Total_Suspense','TotalCases','Active_Cases']]
x_test = test_data[['Tenure_Months','Apps_Proc_Percent','Applied_Premium','NoBenePercent','NoCertPercent','GROSS_AP','G0138_received','Setup_Complete','Total_Suspense','TotalCases','Active_Cases']]
y_train = train_data[['y']]
y_test = test_data[['y']]

In [95]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(x_train, y_train)  

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [96]:
y_pred = classifier.predict(x_test)  
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[138 142 151 398]
 [128 167 158 393]
 [127 145 169 408]
 [  0   0   0   0]]


In [97]:
y_pred[2522]

12

In [98]:
y_test.iloc[2522]

y    1
Name: 182892, dtype: int64

In [99]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          1       0.35      0.17      0.23       829
          2       0.37      0.20      0.26       846
          3       0.35      0.20      0.25       849
         12       0.00      0.00      0.00         0

avg / total       0.36      0.19      0.25      2524



In [100]:
print('Accuracy of Decision Tree classifier on test set: {:.2f}'.format(classifier.score(x_test, y_test)))

Accuracy of Decision Tree classifier on test set: 0.19


In [101]:
y_pred

array([ 3,  3,  1, ..., 12, 12, 12])

In [102]:
from collections import Counter
print(sorted(Counter(mod_data.y).items()))

[(0, 1575), (1, 1558), (2, 1563), (3, 1571), (12, 162940)]


In [141]:
X = mod_data[['Tenure_Months','Apps_Proc_Percent','Applied_Premium','NoBenePercent','NoCertPercent','GROSS_AP','G0138_received','Setup_Complete','Total_Suspense','TotalCases','Active_Cases']]
y = mod_data[['y']]

In [104]:
X = X.iloc[0:100000]
y = y.iloc[0:100000]

In [105]:
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=0)
X_resampled, y_resampled = cc.fit_sample(X, y)
print(sorted(Counter(y_resampled).items()))

[(0, 1040), (1, 1040), (2, 1040), (3, 1040), (12, 1040)]


In [106]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
X_train.shape

(75000, 11)

In [107]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(X_train, y_train) 

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [108]:
y_pred = classifier.predict(X_test)  
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[  207     2     2     1    55]
 [    2    23    51    18   174]
 [    0    36    10    38   180]
 [    0    16    21    15   205]
 [   59   199   205   241 23240]]


In [109]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.77      0.78      0.77       267
          1       0.08      0.09      0.08       268
          2       0.03      0.04      0.04       264
          3       0.05      0.06      0.05       257
         12       0.97      0.97      0.97     23944

avg / total       0.94      0.94      0.94     25000



In [142]:
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_sample(X, y)
print(sorted(Counter(y_resampled).items()))

[(0, 160904), (1, 137055), (2, 132591), (3, 138345), (12, 100411)]


In [111]:
from imblearn.combine import SMOTETomek
smote_tomek = SMOTETomek(random_state=0)
X_resampled, y_resampled = smote_tomek.fit_sample(X, y)
print(sorted(Counter(y_resampled).items()))

[(0, 95665), (1, 93635), (2, 92983), (3, 93767), (12, 93260)]


In [143]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, random_state=0)
X_train.shape
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(X_train, y_train) 

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [144]:
y_pred = classifier.predict(X_test)  
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[40112    22    25    19    40]
 [   43 32944   550   342   381]
 [   28   534 31718   550   349]
 [   27   370   526 33167   420]
 [   40   781   852  1002 22485]]


In [145]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00     40218
          1       0.95      0.96      0.96     34260
          2       0.94      0.96      0.95     33179
          3       0.95      0.96      0.95     34510
         12       0.95      0.89      0.92     25160

avg / total       0.96      0.96      0.96    167327



In [127]:
import xgboost as xgb
from xgboost.sklearn import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [128]:
y_pred = classifier.predict(X_test)  
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[  244     0     0     0    23]
 [    0     1     0     0   267]
 [    0     0     0     0   264]
 [    0     0     0     0   257]
 [   42     2     0     1 23899]]


/home/koushik/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [129]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.85      0.91      0.88       267
          1       0.33      0.00      0.01       268
          2       0.00      0.00      0.00       264
          3       0.00      0.00      0.00       257
         12       0.97      1.00      0.98     23944

avg / total       0.94      0.97      0.95     25000



In [130]:
data.columns

Index([u'Unnamed: 0', u'GRPNUM', u'VALUATION', u'STATUS', u'SIC_Code',
       u'Effective_Date', u'EE_Count', u'Tenure_Months', u'Tenure_Months1',
       u'Apps_Recd', u'Apps_Proc', u'Apps_Proc_Percent', u'Applied_Premium',
       u'AppliedPremium_L1', u'AppliedPremiumL1_Percent', u'AppliedPremium_L2',
       u'AppliedPremiumL2_Percent', u'AppliedPremium_L3',
       u'AppliedPremiumL3_Percent', u'Claims_Total', u'NoBene', u'NoCert',
       u'NoBenePercent', u'NoCertPercent', u'GROSS_AP', u'GROSSAP_L1',
       u'GrossAPL1_Percent', u'GROSSAP_L2', u'GrossAPL2_Percent',
       u'GROSSAP_L3', u'GrossAPL3_Percent', u'Eff_Date', u'Enrollment_Data',
       u'Account_Implementation_Coordinator', u'Account_Service_Coordinator',
       u'G0138_Status_Timestamp', u'Enrollment_Star_Timestamp',
       u'G0138_received', u'Min_Task_Entry_Date', u'Setup_Complete',
       u'Specific_Suspense', u'Unknown_Suspense', u'Total_Suspense',
       u'TotalSuspense_L1', u'TotalSuspenseL1_Percent', u'TotalSuspen

In [183]:
X = mod_data[['Tenure_Months','Tenure_Months1','Apps_Proc_Percent','Applied_Premium','AppliedPremiumL1_Percent','AppliedPremiumL2_Percent','AppliedPremiumL3_Percent','NoBenePercent','NoCertPercent','GrossAPL1_Percent','GrossAPL2_Percent','GrossAPL3_Percent','TotalSuspenseL1_Percent','TotalSuspenseL2_Percent','TotalSuspenseL3_Percent','G0138_received','Setup_Complete','Total_Suspense','TotalCases','Active_Cases','GROSS_AP','Total_Suspense']]
y = mod_data[['y']]

In [197]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3 )

In [207]:
#y_test.shape = (50763,)
#y_test = y_test.reshape(50763,)
y_test.shape

(50763, 1)

In [226]:
y_test = np.array(y_test)
y_test= np.reshape(y_test,(50763,))
y_test.shape

(50763,)

In [ ]:
y_train = np.array(y_train)
y_train= np.reshape(y_trai,(50763,))
y_test.shape

In [199]:
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_sample(X_train, y_train)
print(sorted(Counter(y_resampled).items()))

[(0, 113021), (1, 101323), (2, 99520), (3, 100714), (12, 68837)]


In [200]:
# X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.3 , random_state=0)
# X_train.shape
# X_train = X_resampled
# y_train = y_resampled
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(X_resampled, y_resampled) 

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [227]:
print(sorted(Counter(y_train).items()))
print(sorted(Counter(y_test).items()))

[('y', 1)]
[(0, 460), (1, 475), (2, 485), (3, 470), (12, 48873)]


In [202]:
y_pred = classifier.predict(X_test)  
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
print(classification_report(y_test, y_pred))

[[  425    15     7     3    10]
 [    9    91    86    56   233]
 [    6   101    56    70   252]
 [    4    56    70    49   291]
 [  153  2579  2715  2790 40636]]
             precision    recall  f1-score   support

          0       0.71      0.92      0.80       460
          1       0.03      0.19      0.05       475
          2       0.02      0.12      0.03       485
          3       0.02      0.10      0.03       470
         12       0.98      0.83      0.90     48873

avg / total       0.95      0.81      0.87     50763



In [178]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()  
classifier.fit(X_train, y_train) 

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [179]:
y_pred = classifier.predict(X_test)  
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
print(classification_report(y_test, y_pred))

[[  440    15     4     0     9]
 [   12    81    90    29   277]
 [   10    82    52    42   293]
 [    1    47    49    36   299]
 [  135  1670  1547  1384 44159]]
             precision    recall  f1-score   support

          0       0.74      0.94      0.83       468
          1       0.04      0.17      0.07       489
          2       0.03      0.11      0.05       479
          3       0.02      0.08      0.04       432
         12       0.98      0.90      0.94     48895

avg / total       0.95      0.88      0.91     50763



In [203]:
# X_train = X_resampled
# y_train = y_resampled
import xgboost as xgb
from xgboost.sklearn import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_resampled,y_resampled)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [204]:
y_pred = classifier.predict(X_test)  
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
print(classification_report(y_test, y_pred))

ValueError: feature_names must be unique

In [195]:
y_test.columns

Index([u'y'], dtype='object')

In [196]:
y_train.columns

AttributeError: 'numpy.ndarray' object has no attribute 'columns'